### ISSUE TITLE
Configuration du PA dans SX126X_RF_API_init()

### ISSUE THREAD

**Issue by Manuel-Fostier** [sigfox-tech-radio/sigfox-ep-rf-api-semtech-sx126x#1]
Bonjour, je voudrais signaler un problème dans le fichier `sx126x_rf_api.c`. Lors de la configuration du PA dans la fonction `SX126X_RF_API_init()` à la ligne suivante :
https://github.com/sigfox-tech-radio/sigfox-ep-rf-api-semtech-sx126x/blob/c41b644dc2a570b05aedf4b287b3db0bacef3c87/src/manuf/sx126x_rf_api.c#L388
Celle-ci devrait être remplacée par :
`sx126x_pa_cfg_params.hp_max = sx126x_hw_api_pa_pwr_cfg.pa_config.hp_max;`

Car la première assigne une valeur incorrecte au paramètre hp_max.

**Comment by CedricB31** [comment]
@Manuel-Fostier, effectivement, ce patch est nécessaire au bon fonctionnement du SX1262. Nous validons la modification en interne, elle sera intégrée dans la prochaine release.
